name = "VariationalMC"
uuid = "519ac81d-5865-4374-9f64-28b66ac9043d"
authors = ["Andy Tanjaroon Ly"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LatticeUtilities = "33fcf0eb-3ae3-43db-bfbc-1d92a3639bd1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
DataStructures = "0.18.20"
DelimitedFiles = "1.9.1"
FilePathsBase = "0.9.24"
HDF5 = "0.17.2"
JLD2 = "0.5.10"
LaTeXStrings = "1.4.0"
LatticeUtilities = "2.0.7"
OrderedCollections = "1.7.0"
ProfileView = "1.10.1"
Random = "1.11.0"
Revise = "3.7.1"
TOML = "1.0.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
